import { CategoryOption, InventoryProduct } from './types';

export const mockCategories: CategoryOption[] = [
  { id: 'cat-1', name: 'Avionics & Telemetry', slug: 'avionics' },
  { id: 'cat-2', name: 'Titanium & Fasteners', slug: 'fasteners' },
  { id: 'cat-3', name: 'Thermal Protection', slug: 'thermal' },
  { id: 'cat-4', name: 'Molecular Diagnostics', slug: 'molecular' },
  { id: 'cat-5', name: 'Robotic Consumables', slug: 'robotics' },
];

export const initialMockProducts: InventoryProduct[] = [
  {
    id: 'prod-001',
    organizationId: 'org-aero-01',
    categoryId: 'cat-1',
    categoryName: 'Avionics & Telemetry',
    sku: 'ASD-SEN-9100',
    name: 'Tri-Axis MEMS Inertial Rate Gyroscope Assembly',
    description: 'Space-qualified angular velocity sensor module with low drift and SPI/CAN bus interface.',
    unitPrice: 1450.0,
    costPrice: 890.0,
    stockQuantity: 85,
    reorderPoint: 15,
    status: 'ACTIVE',
    createdAt: '2026-09-01T10:00:00Z',
    updatedAt: '2026-09-05T08:30:00Z',
  },
  {
    id: 'prod-002',
    organizationId: 'org-aero-01',
    categoryId: 'cat-1',
    categoryName: 'Avionics & Telemetry',
    sku: 'ASD-SEN-9250',
    name: 'High-G Precision Triaxial Accelerometer Transducer',
    description: 'Hermetically sealed 500g dynamic accelerometer for atmospheric re-entry telemetry.',
    unitPrice: 820.0,
    costPrice: 460.0,
    stockQuantity: 140,
    reorderPoint: 20,
    status: 'ACTIVE',
    createdAt: '2026-09-02T11:15:00Z',
    updatedAt: '2026-09-04T14:20:00Z',
  },
  {
    id: 'prod-003',
    organizationId: 'org-aero-01',
    categoryId: 'cat-2',
    categoryName: 'Titanium & Fasteners',
    sku: 'ASD-FST-4010',
    name: 'Grade 5 Titanium Hex Flange Bolts (M8 x 40mm, Pack of 50)',
    description: 'Ti-6Al-4V fasteners meeting AMS4928 spec for airframe and propulsion mounting.',
    unitPrice: 260.0,
    costPrice: 135.0,
    stockQuantity: 650,
    reorderPoint: 100,
    status: 'ACTIVE',
    createdAt: '2026-08-28T09:00:00Z',
    updatedAt: '2026-09-05T07:10:00Z',
  },
  {
    id: 'prod-004',
    organizationId: 'org-aero-01',
    categoryId: 'cat-2',
    categoryName: 'Titanium & Fasteners',
    sku: 'ASD-FST-8820',
    name: 'Inconel 718 Self-Locking Reduced Hex Nuts (Pack of 100)',
    description: 'Extreme-temperature nickel superalloy nuts rated up to 650°C continuous service.',
    unitPrice: 380.0,
    costPrice: 210.0,
    stockQuantity: 12, // LOW STOCK (below 75 reorder point)
    reorderPoint: 75,
    status: 'ACTIVE',
    createdAt: '2026-08-29T14:45:00Z',
    updatedAt: '2026-09-05T09:00:00Z',
  },
  {
    id: 'prod-005',
    organizationId: 'org-aero-01',
    categoryId: 'cat-3',
    categoryName: 'Thermal Protection',
    sku: 'ASD-THM-1050',
    name: 'Rigid Ceramic Aerogel Thermal Barrier Tile (300mm x 300mm)',
    description: 'Low-density refractory composite thermal barrier designed for 1400°C peak gradient.',
    unitPrice: 620.0,
    costPrice: 340.0,
    stockQuantity: 4, // LOW STOCK (below 10 reorder point)
    reorderPoint: 10,
    status: 'ACTIVE',
    createdAt: '2026-08-30T16:20:00Z',
    updatedAt: '2026-09-03T11:00:00Z',
  },
  {
    id: 'prod-006',
    organizationId: 'org-aero-01',
    categoryId: 'cat-3',
    categoryName: 'Thermal Protection',
    sku: 'ASD-THM-2010',
    name: 'Silica-Fiber Flexible Insulation Blanket (1000mm x 500mm)',
    description: 'High-purity silica needle-felt blanket for rocket nozzle nacelle thermal insulation.',
    unitPrice: 490.0,
    costPrice: 275.0,
    stockQuantity: 0, // OUT OF STOCK
    reorderPoint: 15,
    status: 'OUT_OF_STOCK',
    createdAt: '2026-08-25T08:00:00Z',
    updatedAt: '2026-09-05T12:00:00Z',
  },
  {
    id: 'prod-007',
    organizationId: 'org-aero-01',
    categoryId: 'cat-4',
    categoryName: 'Molecular Diagnostics',
    sku: 'BVD-PCR-2001',
    name: 'UltraPure Taq 2X Master Mix (1000 Reactions)',
    description: 'Ready-to-use qPCR master mix with hot-start Taq polymerase and dNTPs.',
    unitPrice: 340.0,
    costPrice: 145.0,
    stockQuantity: 210,
    reorderPoint: 30,
    status: 'ACTIVE',
    createdAt: '2026-08-20T10:00:00Z',
    updatedAt: '2026-09-04T16:00:00Z',
  },
  {
    id: 'prod-008',
    organizationId: 'org-aero-01',
    categoryId: 'cat-4',
    categoryName: 'Molecular Diagnostics',
    sku: 'BVD-PCR-4050',
    name: 'Multiplex One-Step RT-qPCR Viral Detection Kit',
    description: 'Clinical diagnostic reverse transcriptase qPCR assay with internal extraction control.',
    unitPrice: 890.0,
    costPrice: 410.0,
    stockQuantity: 65,
    reorderPoint: 15,
    status: 'ACTIVE',
    createdAt: '2026-08-22T13:30:00Z',
    updatedAt: '2026-09-02T10:15:00Z',
  },
  {
    id: 'prod-009',
    organizationId: 'org-aero-01',
    categoryId: 'cat-5',
    categoryName: 'Robotic Consumables',
    sku: 'BVD-AUT-9600',
    name: 'Robotic Filter Tips 200µL (96-Well Rack, 10 Racks/Box)',
    description: 'Sterile, aerosol-barrier pipette tips compatible with automation liquid handlers.',
    unitPrice: 115.0,
    costPrice: 42.0,
    stockQuantity: 580,
    reorderPoint: 100,
    status: 'ACTIVE',
    createdAt: '2026-08-15T09:00:00Z',
    updatedAt: '2026-09-05T06:00:00Z',
  },
  {
    id: 'prod-010',
    organizationId: 'org-aero-01',
    categoryId: 'cat-5',
    categoryName: 'Robotic Consumables',
    sku: 'BVD-AUT-3840',
    name: 'Deep-Well Microplates 384-Well Polypropylene (Box of 50)',
    description: 'Virgin polypropylene SBS-format deep well plates for automated high-throughput screening.',
    unitPrice: 210.0,
    costPrice: 85.0,
    stockQuantity: 0, // OUT OF STOCK
    reorderPoint: 25,
    status: 'OUT_OF_STOCK',
    createdAt: '2026-08-18T15:10:00Z',
    updatedAt: '2026-09-01T11:45:00Z',
  },
  {
    id: 'prod-011',
    organizationId: 'org-aero-01',
    categoryId: 'cat-1',
    categoryName: 'Avionics & Telemetry',
    sku: 'ASD-TEL-3000',
    name: 'MIL-STD S-Band Downlink RF Power Transmitter',
    description: '10W continuous S-band RF transmitter module for satellite ground communication.',
    unitPrice: 3200.0,
    costPrice: 1950.0,
    stockQuantity: 18,
    reorderPoint: 5,
    status: 'DRAFT',
    createdAt: '2026-09-04T12:00:00Z',
    updatedAt: '2026-09-05T14:00:00Z',
  },
  {
    id: 'prod-012',
    organizationId: 'org-aero-01',
    categoryId: 'cat-2',
    categoryName: 'Titanium & Fasteners',
    sku: 'ASD-FST-9900',
    name: 'Legacy Hex Cap Screw (Discontinued Spec)',
    description: 'Superseded by ASD-FST-4010 series. No longer in active production.',
    unitPrice: 95.0,
    costPrice: 40.0,
    stockQuantity: 2,
    reorderPoint: 10,
    status: 'DISCONTINUED',
    createdAt: '2026-05-10T08:00:00Z',
    updatedAt: '2026-08-10T10:00:00Z',
  },
];
